spring:
  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/accounts/**

        - id: transactions-service
          uri: lb://TRANSACTIONS
          predicates:
            - Path=/transactions/**
